const MAXIMAGENESPORPRODUCTO = 5;
const MAXCATEGORIASPORPRODUCTO = 3;
const MINCARACTERESCONTRASENA = 6;
const ROLES = ["ADMIN", "USER"];//esta variable no se enlaza con la base de datos.

module.exports = {
  MAXIMAGENESPORPRODUCTO,
  MAXCATEGORIASPORPRODUCTO,
  MINCARACTERESCONTRASENA,
  ROLES
};
